apiVersion: v1
kind: Service
metadata:
  name: wisecow
spec:
  type: NodePort   # for Minikube/Kind
  selector:
    app: wisecow
  ports:
  - port: 4499
    targetPort: 4499
    nodePort: 30449   # fixed NodePort (range 30000–32767)
